name: Deploy to Local Nginx

on:
  push:
    branches:
      - main # 触发部署的分支

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Local Nginx
        run: |
          cp -R ./dist F:\nginx-1.17.5\nginx.exe
