name: Deploy to Nginx Server

on:
  push:
    branches:
      - main # 触发部署的分支

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Nginx Server
        env:
          HOST: 172.16.77.222
          USERNAME: "hp"
          PASSWORD: "199146cwq"
          PATH_TO_NGINX: F:/nginx-1.17.5/html
        run: |
          echo open $env:HOST >> script.txt
          echo $env:USERNAME >> script.txt
          echo $env:PASSWORD >> script.txt
          echo put -r ./build $env:PATH_TO_NGINX >> script.txt
          echo exit >> script.txt
          .\winscp.com /script=script.txt
          Remove-Item -Path script.txt
