name: Deploy to Nginx Server

on:
  push:
    branches:
      - main # 触发部署的分支

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Nginx Server
        run: |
          $secpasswd = ConvertTo-SecureString '199146cwq' -AsPlainText -Force
          $credentials = New-Object System.Management.Automation.PSCredential ('hp', $secpasswd)
          New-SSHSession -ComputerName 172.16.77.222 -Credential $credentials -AcceptKey -Force
          Copy-Item -Recurse -Path ./dist -Destination F:/nginx-1.17.5/html -ToSession $SSHSession
          Remove-SSHSession -SSHSession $SSHSession
