name: Deploy to Nginx Server

on:
  push:
    branches:
      - main # 触发部署的分支

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Nginx Server
        uses: appleboy/scp-action@master
        with:
          host: 172.16.77.222
          username: hp
          key: ${{ secrets.CWQCICDSECRET }}
          source: ./dist
          target: F:/nginx-1.17.5/html
